# tools/select_models.py
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any, Dict

import yaml


def _project_root() -> Path:
    # .../tools/select_models.py -> project root
    return Path(__file__).resolve().parents[1]


def _must(d: Dict[str, Any], key: str) -> Any:
    if key not in d:
        raise RuntimeError(f"Missing required key '{key}' in config")
    return d[key]


def _pick_uri(cfg: Dict[str, Any], block: str, family: str) -> str:
    reg = _must(cfg, "registry")
    sel = _must(cfg, "selection")

    chosen_family = _must(sel, block)
    if chosen_family not in ("sklearn", "lgbm"):
        raise RuntimeError(f"Invalid selection.{block}='{chosen_family}'. Use: sklearn|lgbm")

    block_map = _must(reg, block)
    if chosen_family not in block_map:
        raise RuntimeError(f"registry.{block} has no key '{chosen_family}'")

    uri = str(block_map[chosen_family]).strip()
    if not uri.startswith("models:/"):
        raise RuntimeError(
            f"registry.{block}.{chosen_family} must start with 'models:/', got: {uri}"
        )
    return uri


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate .env for API from YAML model_map")
    parser.add_argument(
        "--config",
        default=str(_project_root() / "configs" / "model_map.yaml"),
        help="Path to model_map.yaml",
    )
    parser.add_argument(
        "--out",
        default=str(_project_root() / ".env.api"),
        help="Output env file path (default: .env.api in project root)",
    )
    parser.add_argument(
        "--also-k8s-env",
        default="",
        help="Optional additional output env file path (e.g. k8s/secret.env)",
    )
    args = parser.parse_args()

    cfg_path = Path(args.config).resolve()
    if not cfg_path.exists():
        raise RuntimeError(f"Config not found: {cfg_path}")

    with cfg_path.open("r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    mlflow_block = _must(cfg, "mlflow")
    tracking_uri = str(_must(mlflow_block, "tracking_uri")).strip()

    health_uri = _pick_uri(cfg, "health", "selection")
    h1_uri = _pick_uri(cfg, "trunk_h1", "selection")
    h7_uri = _pick_uri(cfg, "trunk_h7", "selection")

    lines = [
        "# AUTOGENERATED by tools/select_models.py",
        f"MLFLOW_TRACKING_URI={tracking_uri}",
        f"HEALTH_MODEL_URI={health_uri}",
        f"FORECAST_MODEL_H1_URI={h1_uri}",
        f"FORECAST_MODEL_H7_URI={h7_uri}",
        "",
    ]

    out_path = Path(args.out).resolve()
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"✅ wrote: {out_path}")

    if args.also_k8s_env:
        k8s_out = Path(args.also_k8s_env)
        if not k8s_out.is_absolute():
            k8s_out = (_project_root() / k8s_out).resolve()
        k8s_out.parent.mkdir(parents=True, exist_ok=True)
        k8s_out.write_text("\n".join(lines), encoding="utf-8")
        print(f"✅ wrote: {k8s_out}")

    print("\n--- preview ---")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
